# Generated by Django 4.1.7 on 2023-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='type_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
