# Generated by Django 4.1.7 on 2023-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_register_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='type_id',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
