# Generated by Django 4.1.7 on 2023-05-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_remove_borrowed_to_who_remove_borrowed_what_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popular',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recommended',
            options={},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='fullname',
            new_name='addressname',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.location'),
        ),
    ]
