# Generated by Django 4.1.7 on 2023-05-15 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerceapp', '0009_profile_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='owner',
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
