# Generated by Django 4.1.7 on 2023-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_remove_profile_address_locationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='address_type',
            field=models.CharField(choices=[('home', 'homeaddress'), ('office', 'officeaddress'), ('currentposition', 'currentpositionaddress')], default=2, max_length=300),
            preserve_default=False,
        ),
    ]
