# Generated by Django 4.1.7 on 2023-05-15 13:13

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_locationtype_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressname', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('tombon', models.CharField(blank=True, max_length=1024, null=True)),
                ('amphure', models.CharField(blank=True, max_length=1024, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True)),
                ('province', models.CharField(blank=True, max_length=1024, null=True)),
                ('city', models.CharField(default='Thailand', max_length=1024)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('type_id', models.IntegerField(blank=True, default=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressname', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('tombon', models.CharField(blank=True, max_length=1024, null=True)),
                ('amphure', models.CharField(blank=True, max_length=1024, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True)),
                ('province', models.CharField(blank=True, max_length=1024, null=True)),
                ('city', models.CharField(default='Thailand', max_length=1024)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('type_id', models.IntegerField(blank=True, default=3, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='Location1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='homeaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.location1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='officeaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.location2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='presentpositionaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.location3'),
        ),
    ]
