# Generated by Django 4.1.7 on 2023-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_location2_location3_rename_location_location1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location1',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location1',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location2',
            name='type_id',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='location3',
            name='type_id',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
